In [6]:
import pandas as pd
import re

df = pd.read_csv('Coachella-2015-2-DFE.csv', encoding='latin1')

# Show the first 2 rows of the dataset
print("=== First 2 rows of the data ===")
display(df.head(2))

=== First 2 rows of the data ===

,coachella_sentiment,coachella_yn,name,retweet_count,text,tweet_coord,tweet_created,tweet_id,tweet_location,user_timezone
0,positive,yes,kokombil,0,#Coachella2015 tickets selling out in less tha...,"[0.0, 0.0]",1/7/15 15:02,5.529630e+17,NaN,Quito
1,positive,yes,MisssTaraaa10,2,RT @sudsybuddy: WAIT THIS IS ABSOLUTE FIRE _ÙÓ...,NaN,1/7/15 15:02,5.529630e+17,united states,NaN

In [7]:
# Find all hashtags and put them in a new 'hashtags' column
df['hashtags'] = df['text'].apply(lambda x: re.findall(r'#\w+', str(x)))

# Find all email addresses and put them in a new 'emails' column
df['emails'] = df['text'].apply(lambda x: re.findall(r'[\w\.-]+@[\w\.-]+\.\w+', str(x)))

# Show the text, hashtags, and emails side by side
print("Hashtags and emails extracted successfully!")
display(df[['text', 'hashtags', 'emails']].head(3))

Hashtags and emails extracted successfully!

,text,hashtags,emails
0,#Coachella2015 tickets selling out in less tha...,[#Coachella2015],[]
1,RT @sudsybuddy: WAIT THIS IS ABSOLUTE FIRE _ÙÓ...,[#Coachella2015],[]
2,#Coachella2015 #VIP passes secured! See you th...,"[#Coachella2015, #VIP]",[]

In [8]:
# 1. Remove usernames that start with '@'
def remove_usernames(text):
    return re.sub(r'@\w+', '', str(text))

# 2. Remove web links
def remove_links(text):
    return re.sub(r'https?://\S+|www\.\S+', '', str(text))

# 3. Remove non-ASCII symbols
def remove_non_ascii_symbols(text):
    return ''.join([i for i in str(text) if ord(i) < 128])

# 4. Convert all text to lowercase
def to_lower(text):
    return str(text).lower()

# 5. Remove common stop words
def remove_stop_words(text):
    stop_words = set(['the', 'a', 'an', 'and', 'in', 'on', 'at', 'for', 'to', 'of', 'is', 'are', 'it', 'this', 'that', 'rt'])
    words = str(text).split()
    filtered_words = [w for w in words if w not in stop_words]
    return ' '.join(filtered_words)

# 6. Remove numbers/digits
def remove_digits(text):
    return re.sub(r'\d+', '', str(text))

# 7. Remove punctuation marks and special characters
def remove_special_characters(text):
    return re.sub(r'[^a-zA-Z0-9\s]', '', str(text))

print("All cleaning functions are ready!")

All cleaning functions are ready!

In [9]:
# Create a new column called 'cleaned_text' and apply each function one by one
df['cleaned_text'] = df['text']
df['cleaned_text'] = df['cleaned_text'].apply(remove_usernames)
df['cleaned_text'] = df['cleaned_text'].apply(remove_links)
df['cleaned_text'] = df['cleaned_text'].apply(remove_non_ascii_symbols)
df['cleaned_text'] = df['cleaned_text'].apply(to_lower)
df['cleaned_text'] = df['cleaned_text'].apply(remove_stop_words)
df['cleaned_text'] = df['cleaned_text'].apply(remove_digits)
df['cleaned_text'] = df['cleaned_text'].apply(remove_special_characters)

# Compare original text and cleaned text
print("=== Final Cleaned Results ===")
display(df[['text', 'cleaned_text']].head(5))

=== Final Cleaned Results ===

,text,cleaned_text
0,#Coachella2015 tickets selling out in less tha...,coachella tickets selling out less than minutes
1,RT @sudsybuddy: WAIT THIS IS ABSOLUTE FIRE _ÙÓ...,wait absolute fire coachella
2,#Coachella2015 #VIP passes secured! See you th...,coachella vip passes secured see you there bit...
3,PhillyÛªs @warondrugsjams will play #Coachell...,phillys will play coachella amp govball watch ...
4,If briana and her mom out to #Coachella2015 i...,if briana her mom out coachella im out with th...